# Generated by Django 4.0.6 on 2023-09-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2_crud_app', '0002_alter_person_options_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
